Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -110,11 +110,12 @@ jobs:
           command: git push https://heroku:84a6e6ef-89a6-4750-9073-a451f0b53d29@git.heroku.com/damp-sea-12569.git HEAD:main
       - run:
           name: Smoke Test
-          command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://damp-sea-12569.herokuapp.com/`
-                    if [ "$HTTPCODE" -ne 200 ];then
-                      echo "heroku app not responding, failing deploy"
-                    exit 1
-                  fi
+          command: | 
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://damp-sea-12569.herokuapp.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+                echo "heroku app not responding, failing deploy"
+            exit 1
+            fi
 
 workflows:
   version: 2
